[build]
builder = "nixpacks"
buildCommand = "npm install && pip3 install -U yt-dlp"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"

[nixpacks]
aptPkgs = ["ffmpeg", "python3", "python3-pip"]
